package se.phan.redacted.textengine.parser

import ch.tutteli.atrium.api.fluent.en_GB.toContainExactly
import ch.tutteli.atrium.api.verbs.expect
import se.phan.redacted.textengine.Newline
import se.phan.redacted.textengine.Punctuation
import se.phan.redacted.textengine.Space
import se.phan.redacted.textengine.Word
import kotlin.test.Test

class TextParserWikipediaNovelTest {

    @Test
    fun `parse wikipedia novel entry`() {
        val str = """
            Dune is a 1965 epic science fiction novel by American author Frank Herbert, originally published as two separate serials in Analog magazine. It tied with Roger Zelazny's This Immortal for the Hugo Award in 1966 and it won the inaugural Nebula Award for Best Novel. It is the first installment of the Dune saga. In 2003, it was described as the world's best-selling science fiction novel.

            Dune is set in the distant future amidst a feudal interstellar society in which various noble houses control planetary fiefs. It tells the story of young Paul Atreides, whose family accepts the stewardship of the planet Arrakis. While the planet is an inhospitable and sparsely populated desert wasteland, it is the only source of melange, or "spice", a drug that extends life and enhances mental abilities. Melange is also necessary for space navigation, which requires a kind of multidimensional awareness and foresight that only the drug provides. As melange can only be produced on Arrakis, control of the planet is a coveted and dangerous undertaking. The story explores the multilayered interactions of politics, religion, ecology, technology, and human emotion, as the factions of the empire confront each other in a struggle for the control of Arrakis and its spice.

            Herbert wrote five sequels: Dune Messiah, Children of Dune, God Emperor of Dune, Heretics of Dune, and Chapterhouse: Dune. Following Herbert's death in 1986, his son Brian Herbert and author Kevin J. Anderson continued the series in over a dozen additional novels since 1999.

            Adaptations of the novel to cinema have been notoriously difficult and complicated. In the 1970s, cult filmmaker Alejandro Jodorowsky attempted to make a film based on the novel. After three years of development, the project was canceled due to a constantly growing budget. In 1984, a film adaptation directed by David Lynch was released to a mostly negative response from critics and failed at the box office. The book was also adapted into the 2000 Sci-Fi Channel miniseries Frank Herbert's Dune and its 2003 sequel Frank Herbert's Children of Dune (which combines the events of Dune Messiah and Children of Dune). A second film adaptation directed by Denis Villeneuve was released on October 21, 2021, to generally positive reviews from critics and grossed ${'$'}401 million worldwide. It also went on to win six Academy Awards. Villeneuve's film was essentially the first half of the original novel, and a sequel, which will cover the remaining story, has begun production and is set for release in 2023. The series has been used as the basis for several board, role-playing, and video games.

            Since 2009, the names of planets from the Dune novels have been adopted for the real-life nomenclature of plains and other features on Saturn's moon Titan.
        """.trimIndent()

        val text = TextParser.parse(str)

        expect(text.items).toContainExactly(
            Word("Dune", redacted = true),
            Space,
            Word("is", redacted = true),
            Space,
            Word("a", redacted = true),
            Space,
            Word("1965", redacted = true),
            Space,
            Word("epic", redacted = true),
            Space,
            Word("science", redacted = true),
            Space,
            Word("fiction", redacted = true),
            Space,
            Word("novel", redacted = true),
            Space,
            Word("by", redacted = true),
            Space,
            Word("American", redacted = true),
            Space,
            Word("author", redacted = true),
            Space,
            Word("Frank", redacted = true),
            Space,
            Word("Herbert", redacted = true),
            Punctuation(','),
            Space,
            Word("originally", redacted = true),
            Space,
            Word("published", redacted = true),
            Space,
            Word("as", redacted = true),
            Space,
            Word("two", redacted = true),
            Space,
            Word("separate", redacted = true),
            Space,
            Word("serials", redacted = true),
            Space,
            Word("in", redacted = true),
            Space,
            Word("Analog", redacted = true),
            Space,
            Word("magazine", redacted = true),
            Punctuation('.'),
            Space,

            Word("It", redacted = true),
            Space,
            Word("tied", redacted = true),
            Space,
            Word("with", redacted = true),
            Space,
            Word("Roger", redacted = true),
            Space,
            Word("Zelazny", redacted = true),
            Punctuation('\''),
            Word("s", redacted = true),
            Space,
            Word("This", redacted = true),
            Space,
            Word("Immortal", redacted = true),
            Space,
            Word("for", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("Hugo", redacted = true),
            Space,
            Word("Award", redacted = true),
            Space,
            Word("in", redacted = true),
            Space,
            Word("1966", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("it", redacted = true),
            Space,
            Word("won", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("inaugural", redacted = true),
            Space,
            Word("Nebula", redacted = true),
            Space,
            Word("Award", redacted = true),
            Space,
            Word("for", redacted = true),
            Space,
            Word("Best", redacted = true),
            Space,
            Word("Novel", redacted = true),
            Punctuation('.'),
            Space,

            Word("It", redacted = true),
            Space,
            Word("is", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("first", redacted = true),
            Space,
            Word("installment", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("Dune", redacted = true),
            Space,
            Word("saga", redacted = true),
            Punctuation('.'),
            Space,

            Word("In", redacted = true),
            Space,
            Word("2003", redacted = true),
            Punctuation(','),
            Space,
            Word("it", redacted = true),
            Space,
            Word("was", redacted = true),
            Space,
            Word("described", redacted = true),
            Space,
            Word("as", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("world", redacted = true),
            Punctuation('\''),
            Word("s", redacted = true),
            Space,
            Word("best", redacted = true),
            Punctuation('-'),
            Word("selling", redacted = true),
            Space,
            Word("science", redacted = true),
            Space,
            Word("fiction", redacted = true),
            Space,
            Word("novel", redacted = true),
            Punctuation('.'),

            Newline,
            Newline,

            Word("Dune", redacted = true),
            Space,
            Word("is", redacted = true),
            Space,
            Word("set", redacted = true),
            Space,
            Word("in", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("distant", redacted = true),
            Space,
            Word("future", redacted = true),
            Space,
            Word("amidst", redacted = true),
            Space,
            Word("a", redacted = true),
            Space,
            Word("feudal", redacted = true),
            Space,
            Word("interstellar", redacted = true),
            Space,
            Word("society", redacted = true),
            Space,
            Word("in", redacted = true),
            Space,
            Word("which", redacted = true),
            Space,
            Word("various", redacted = true),
            Space,
            Word("noble", redacted = true),
            Space,
            Word("houses", redacted = true),
            Space,
            Word("control", redacted = true),
            Space,
            Word("planetary", redacted = true),
            Space,
            Word("fiefs", redacted = true),
            Punctuation('.'),
            Space,

            Word("It", redacted = true),
            Space,
            Word("tells", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("story", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("young", redacted = true),
            Space,
            Word("Paul", redacted = true),
            Space,
            Word("Atreides", redacted = true),
            Punctuation(','),
            Space,
            Word("whose", redacted = true),
            Space,
            Word("family", redacted = true),
            Space,
            Word("accepts", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("stewardship", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("planet", redacted = true),
            Space,
            Word("Arrakis", redacted = true),
            Punctuation('.'),
            Space,

            Word("While", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("planet", redacted = true),
            Space,
            Word("is", redacted = true),
            Space,
            Word("an", redacted = true),
            Space,
            Word("inhospitable", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("sparsely", redacted = true),
            Space,
            Word("populated", redacted = true),
            Space,
            Word("desert", redacted = true),
            Space,
            Word("wasteland", redacted = true),
            Punctuation(','),
            Space,
            Word("it", redacted = true),
            Space,
            Word("is", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("only", redacted = true),
            Space,
            Word("source", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("melange", redacted = true),
            Punctuation(','),
            Space,
            Word("or", redacted = true),
            Space,
            Punctuation('"'),
            Word("spice", redacted = true),
            Punctuation('"'),
            Punctuation(','),
            Space,
            Word("a", redacted = true),
            Space,
            Word("drug", redacted = true),
            Space,
            Word("that", redacted = true),
            Space,
            Word("extends", redacted = true),
            Space,
            Word("life", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("enhances", redacted = true),
            Space,
            Word("mental", redacted = true),
            Space,
            Word("abilities", redacted = true),
            Punctuation('.'),
            Space,

            Word("Melange", redacted = true),
            Space,
            Word("is", redacted = true),
            Space,
            Word("also", redacted = true),
            Space,
            Word("necessary", redacted = true),
            Space,
            Word("for", redacted = true),
            Space,
            Word("space", redacted = true),
            Space,
            Word("navigation", redacted = true),
            Punctuation(','),
            Space,
            Word("which", redacted = true),
            Space,
            Word("requires", redacted = true),
            Space,
            Word("a", redacted = true),
            Space,
            Word("kind", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("multidimensional", redacted = true),
            Space,
            Word("awareness", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("foresight", redacted = true),
            Space,
            Word("that", redacted = true),
            Space,
            Word("only", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("drug", redacted = true),
            Space,
            Word("provides", redacted = true),
            Punctuation('.'),
            Space,

            Word("As", redacted = true),
            Space,
            Word("melange", redacted = true),
            Space,
            Word("can", redacted = true),
            Space,
            Word("only", redacted = true),
            Space,
            Word("be", redacted = true),
            Space,
            Word("produced", redacted = true),
            Space,
            Word("on", redacted = true),
            Space,
            Word("Arrakis", redacted = true),
            Punctuation(','),
            Space,
            Word("control", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("planet", redacted = true),
            Space,
            Word("is", redacted = true),
            Space,
            Word("a", redacted = true),
            Space,
            Word("coveted", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("dangerous", redacted = true),
            Space,
            Word("undertaking", redacted = true),
            Punctuation('.'),
            Space,

            Word("The", redacted = true),
            Space,
            Word("story", redacted = true),
            Space,
            Word("explores", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("multilayered", redacted = true),
            Space,
            Word("interactions", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("politics", redacted = true),
            Punctuation(','),
            Space,
            Word("religion", redacted = true),
            Punctuation(','),
            Space,
            Word("ecology", redacted = true),
            Punctuation(','),
            Space,
            Word("technology", redacted = true),
            Punctuation(','),
            Space,
            Word("and", redacted = true),
            Space,
            Word("human", redacted = true),
            Space,
            Word("emotion", redacted = true),
            Punctuation(','),
            Space,
            Word("as", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("factions", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("empire", redacted = true),
            Space,
            Word("confront", redacted = true),
            Space,
            Word("each", redacted = true),
            Space,
            Word("other", redacted = true),
            Space,
            Word("in", redacted = true),
            Space,
            Word("a", redacted = true),
            Space,
            Word("struggle", redacted = true),
            Space,
            Word("for", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("control", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("Arrakis", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("its", redacted = true),
            Space,
            Word("spice", redacted = true),
            Punctuation('.'),

            Newline,
            Newline,

            Word("Herbert", redacted = true),
            Space,
            Word("wrote", redacted = true),
            Space,
            Word("five", redacted = true),
            Space,
            Word("sequels", redacted = true),
            Punctuation(':'),
            Space,
            Word("Dune", redacted = true),
            Space,
            Word("Messiah", redacted = true),
            Punctuation(','),
            Space,
            Word("Children", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("Dune", redacted = true),
            Punctuation(','),
            Space,
            Word("God", redacted = true),
            Space,
            Word("Emperor", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("Dune", redacted = true),
            Punctuation(','),
            Space,
            Word("Heretics", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("Dune", redacted = true),
            Punctuation(','),
            Space,
            Word("and", redacted = true),
            Space,
            Word("Chapterhouse", redacted = true),
            Punctuation(':'),
            Space,
            Word("Dune", redacted = true),
            Punctuation('.'),
            Space,

            Word("Following", redacted = true),
            Space,
            Word("Herbert", redacted = true),
            Punctuation('\''),
            Word("s", redacted = true),
            Space,
            Word("death", redacted = true),
            Space,
            Word("in", redacted = true),
            Space,
            Word("1986", redacted = true),
            Punctuation(','),
            Space,
            Word("his", redacted = true),
            Space,
            Word("son", redacted = true),
            Space,
            Word("Brian", redacted = true),
            Space,
            Word("Herbert", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("author", redacted = true),
            Space,
            Word("Kevin", redacted = true),
            Space,
            Word("J", redacted = true),
            Punctuation('.'),
            Space,
            Word("Anderson", redacted = true),
            Space,
            Word("continued", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("series", redacted = true),
            Space,
            Word("in", redacted = true),
            Space,
            Word("over", redacted = true),
            Space,
            Word("a", redacted = true),
            Space,
            Word("dozen", redacted = true),
            Space,
            Word("additional", redacted = true),
            Space,
            Word("novels", redacted = true),
            Space,
            Word("since", redacted = true),
            Space,
            Word("1999", redacted = true),
            Punctuation('.'),

            Newline,
            Newline,

            Word("Adaptations", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("novel", redacted = true),
            Space,
            Word("to", redacted = true),
            Space,
            Word("cinema", redacted = true),
            Space,
            Word("have", redacted = true),
            Space,
            Word("been", redacted = true),
            Space,
            Word("notoriously", redacted = true),
            Space,
            Word("difficult", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("complicated", redacted = true),
            Punctuation('.'),
            Space,

            Word("In", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("1970s", redacted = true),
            Punctuation(','),
            Space,
            Word("cult", redacted = true),
            Space,
            Word("filmmaker", redacted = true),
            Space,
            Word("Alejandro", redacted = true),
            Space,
            Word("Jodorowsky", redacted = true),
            Space,
            Word("attempted", redacted = true),
            Space,
            Word("to", redacted = true),
            Space,
            Word("make", redacted = true),
            Space,
            Word("a", redacted = true),
            Space,
            Word("film", redacted = true),
            Space,
            Word("based", redacted = true),
            Space,
            Word("on", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("novel", redacted = true),
            Punctuation('.'),
            Space,

            Word("After", redacted = true),
            Space,
            Word("three", redacted = true),
            Space,
            Word("years", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("development", redacted = true),
            Punctuation(','),
            Space,
            Word("the", redacted = true),
            Space,
            Word("project", redacted = true),
            Space,
            Word("was", redacted = true),
            Space,
            Word("canceled", redacted = true),
            Space,
            Word("due", redacted = true),
            Space,
            Word("to", redacted = true),
            Space,
            Word("a", redacted = true),
            Space,
            Word("constantly", redacted = true),
            Space,
            Word("growing", redacted = true),
            Space,
            Word("budget", redacted = true),
            Punctuation('.'),
            Space,

            Word("In", redacted = true),
            Space,
            Word("1984", redacted = true),
            Punctuation(','),
            Space,
            Word("a", redacted = true),
            Space,
            Word("film", redacted = true),
            Space,
            Word("adaptation", redacted = true),
            Space,
            Word("directed", redacted = true),
            Space,
            Word("by", redacted = true),
            Space,
            Word("David", redacted = true),
            Space,
            Word("Lynch", redacted = true),
            Space,
            Word("was", redacted = true),
            Space,
            Word("released", redacted = true),
            Space,
            Word("to", redacted = true),
            Space,
            Word("a", redacted = true),
            Space,
            Word("mostly", redacted = true),
            Space,
            Word("negative", redacted = true),
            Space,
            Word("response", redacted = true),
            Space,
            Word("from", redacted = true),
            Space,
            Word("critics", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("failed", redacted = true),
            Space,
            Word("at", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("box", redacted = true),
            Space,
            Word("office", redacted = true),
            Punctuation('.'),
            Space,

            Word("The", redacted = true),
            Space,
            Word("book", redacted = true),
            Space,
            Word("was", redacted = true),
            Space,
            Word("also", redacted = true),
            Space,
            Word("adapted", redacted = true),
            Space,
            Word("into", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("2000", redacted = true),
            Space,
            Word("Sci", redacted = true),
            Punctuation('-'),
            Word("Fi", redacted = true),
            Space,
            Word("Channel", redacted = true),
            Space,
            Word("miniseries", redacted = true),
            Space,
            Word("Frank", redacted = true),
            Space,
            Word("Herbert", redacted = true),
            Punctuation('\''),
            Word("s", redacted = true),
            Space,
            Word("Dune", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("its", redacted = true),
            Space,
            Word("2003", redacted = true),
            Space,
            Word("sequel", redacted = true),
            Space,
            Word("Frank", redacted = true),
            Space,
            Word("Herbert", redacted = true),
            Punctuation('\''),
            Word("s", redacted = true),
            Space,
            Word("Children", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("Dune", redacted = true),
            Space,
            Punctuation('('),
            Word("which", redacted = true),
            Space,
            Word("combines", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("events", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("Dune", redacted = true),
            Space,
            Word("Messiah", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("Children", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("Dune", redacted = true),
            Punctuation(')'),
            Punctuation('.'),
            Space,

            Word("A", redacted = true),
            Space,
            Word("second", redacted = true),
            Space,
            Word("film", redacted = true),
            Space,
            Word("adaptation", redacted = true),
            Space,
            Word("directed", redacted = true),
            Space,
            Word("by", redacted = true),
            Space,
            Word("Denis", redacted = true),
            Space,
            Word("Villeneuve", redacted = true),
            Space,
            Word("was", redacted = true),
            Space,
            Word("released", redacted = true),
            Space,
            Word("on", redacted = true),
            Space,
            Word("October", redacted = true),
            Space,
            Word("21", redacted = true),
            Punctuation(','),
            Space,
            Word("2021", redacted = true),
            Punctuation(','),
            Space,
            Word("to", redacted = true),
            Space,
            Word("generally", redacted = true),
            Space,
            Word("positive", redacted = true),
            Space,
            Word("reviews", redacted = true),
            Space,
            Word("from", redacted = true),
            Space,
            Word("critics", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("grossed", redacted = true),
            Space,
            Punctuation('$'),
            Word("401", redacted = true),
            Space,
            Word("million", redacted = true),
            Space,
            Word("worldwide", redacted = true),
            Punctuation('.'),
            Space,

            Word("It", redacted = true),
            Space,
            Word("also", redacted = true),
            Space,
            Word("went", redacted = true),
            Space,
            Word("on", redacted = true),
            Space,
            Word("to", redacted = true),
            Space,
            Word("win", redacted = true),
            Space,
            Word("six", redacted = true),
            Space,
            Word("Academy", redacted = true),
            Space,
            Word("Awards", redacted = true),
            Punctuation('.'),
            Space,

            Word("Villeneuve", redacted = true),
            Punctuation('\''),
            Word("s", redacted = true),
            Space,
            Word("film", redacted = true),
            Space,
            Word("was", redacted = true),
            Space,
            Word("essentially", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("first", redacted = true),
            Space,
            Word("half", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("original", redacted = true),
            Space,
            Word("novel", redacted = true),
            Punctuation(','),
            Space,
            Word("and", redacted = true),
            Space,
            Word("a", redacted = true),
            Space,
            Word("sequel", redacted = true),
            Punctuation(','),
            Space,
            Word("which", redacted = true),
            Space,
            Word("will", redacted = true),
            Space,
            Word("cover", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("remaining", redacted = true),
            Space,
            Word("story", redacted = true),
            Punctuation(','),
            Space,
            Word("has", redacted = true),
            Space,
            Word("begun", redacted = true),
            Space,
            Word("production", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("is", redacted = true),
            Space,
            Word("set", redacted = true),
            Space,
            Word("for", redacted = true),
            Space,
            Word("release", redacted = true),
            Space,
            Word("in", redacted = true),
            Space,
            Word("2023", redacted = true),
            Punctuation('.'),
            Space,

            Word("The", redacted = true),
            Space,
            Word("series", redacted = true),
            Space,
            Word("has", redacted = true),
            Space,
            Word("been", redacted = true),
            Space,
            Word("used", redacted = true),
            Space,
            Word("as", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("basis", redacted = true),
            Space,
            Word("for", redacted = true),
            Space,
            Word("several", redacted = true),
            Space,
            Word("board", redacted = true),
            Punctuation(','),
            Space,
            Word("role", redacted = true),
            Punctuation('-'),
            Word("playing", redacted = true),
            Punctuation(','),
            Space,
            Word("and", redacted = true),
            Space,
            Word("video", redacted = true),
            Space,
            Word("games", redacted = true),
            Punctuation('.'),

            Newline,
            Newline,

            Word("Since", redacted = true),
            Space,
            Word("2009", redacted = true),
            Punctuation(','),
            Space,
            Word("the", redacted = true),
            Space,
            Word("names", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("planets", redacted = true),
            Space,
            Word("from", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("Dune", redacted = true),
            Space,
            Word("novels", redacted = true),
            Space,
            Word("have", redacted = true),
            Space,
            Word("been", redacted = true),
            Space,
            Word("adopted", redacted = true),
            Space,
            Word("for", redacted = true),
            Space,
            Word("the", redacted = true),
            Space,
            Word("real", redacted = true),
            Punctuation('-'),
            Word("life", redacted = true),
            Space,
            Word("nomenclature", redacted = true),
            Space,
            Word("of", redacted = true),
            Space,
            Word("plains", redacted = true),
            Space,
            Word("and", redacted = true),
            Space,
            Word("other", redacted = true),
            Space,
            Word("features", redacted = true),
            Space,
            Word("on", redacted = true),
            Space,
            Word("Saturn", redacted = true),
            Punctuation('\''),
            Word("s", redacted = true),
            Space,
            Word("moon", redacted = true),
            Space,
            Word("Titan", redacted = true),
            Punctuation('.')
        )
    }
}